theme: jekyll-theme-minimal

#title: AMIDiNe
#description: Analytical Middleware for Informed Distribution Networks

#logo: assets/images/amidine_logo_colour.png

sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."

plugins:
  - jekyll-gist
