theme: jekyll-theme-minimal

title: 
description: Analytical Middleware for Informed Distribution Networks

logo: assets/images/amidine_logo_regular_colour.png

sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."

plugins:
  - jekyll-gist
